server:
  port: 80

  build.name: ABC-Tech API
  build.version: 0.0.4

spring:
  datasource:
    #DB_HOSTNAME=localhost;DB_PORT=3306;DB_NAME=abctech;DB_USERNAME=root;DB_PASSWORD=Fiap1234
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
